name: flutter_snake_navigation_bar_example
description: Demonstrates how to use the flutter_snake_navigation_bar plugin.
version: 0.5.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  snake_navigation_bar:
    path: ../


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: SourceSerifPro
      fonts:
        - asset: fonts/SourceSerifPro-Bold.ttf

    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: fonts/Ubuntu-Light.ttf
          weight: 200

    - family: IconFont
      fonts:
        - asset: fonts/IconFont.ttf